/*global systemDictionary:true */
'use strict';

systemDictionary = {
  "Client ID": {
    "en": "Client ID",
    "de": "Client ID",
    "ru": "Идентификатор клиента",
    "pt": "ID do cliente",
    "nl": "Klant-ID",
    "fr": "Identifiant client",
    "it": "ID cliente",
    "es": "ID de cliente",
    "pl": "Identyfikator klienta",
    "uk": "ID клієнта",
    "zh-cn": "客户ID"
  },
  "Client Secret": {
    "en": "Client Secret",
    "de": "Client Secret",
    "ru": "Секрет клиента",
    "pt": "Segredo do cliente",
    "nl": "Klantgeheim",
    "fr": "Secret client",
    "it": "Segreto del cliente",
    "es": "Secreto del cliente",
    "pl": "Sekret Klienta",
    "uk": "Секрет клієнта",
    "zh-cn": "客户秘密"
  },
  "Copy Public Key": {
    "en": "Copy Public Key",
    "de": "Public Key kopieren",
    "ru": "Скопировать открытый ключ",
    "pt": "Copiar chave pública",
    "nl": "Kopieer de publieke sleutel",
    "fr": "Copier la clé publique",
    "it": "Copia chiave pubblica",
    "es": "Copiar clave pública",
    "pl": "Skopiuj klucz publiczny",
    "uk": "Копіювати відкритий ключ",
    "zh-cn": "复制公钥"
  },
  "Exclude device IDs (comma separated)": {
    "en": "Exclude device IDs (comma separated)",
    "de": "Geräte-IDs ausschließen (kommagetrennt)",
    "ru": "Исключить идентификаторы устройств (через запятую)",
    "pt": "Excluir IDs de dispositivos (separados por vírgula)",
    "nl": "Apparaat-ID's uitsluiten (door komma's gescheiden)",
    "fr": "Exclure les ID d'appareil (séparés par des virgules)",
    "it": "Escludi ID dispositivo (separati da virgole)",
    "es": "Excluir ID de dispositivos (separados por comas)",
    "pl": "Wyklucz identyfikatory urządzeń (oddzielone przecinkami)",
    "uk": "Виключити ідентифікатори пристроїв (розділені комами)",
    "zh-cn": "排除设备 ID（以逗号分隔）"
  },
  "Exclude objects for update (comma separated)": {
    "en": "Exclude objects for update (comma separated)",
    "de": "Objekte vom Update ausschließen (kommagetrennt)",
    "ru": "Исключить объекты для обновления (через запятую)",
    "pt": "Excluir objetos para atualização (separados por vírgula)",
    "nl": "Objecten uitsluiten voor update (door komma's gescheiden)",
    "fr": "Exclure les objets pour la mise à jour (séparés par des virgules)",
    "it": "Escludi oggetti per l'aggiornamento (separati da virgole)",
    "es": "Excluir objetos para actualización (separados por comas)",
    "pl": "Wyklucz obiekty do aktualizacji (oddzielone przecinkami)",
    "uk": "Виключити об’єкти для оновлення (розділені комами)",
    "zh-cn": "排除更新对象（逗号分隔）"
  },
  "FleetKey Domain": {
    "en": "FleetKey Domain (e.g. abc123.fleetkey.net)",
    "de": "FleetKey Domain (z.B. abc123.fleetkey.net)",
    "ru": "Домен FleetKey (например, abc123.fleetkey.net)",
    "pt": "Domínio FleetKey (por exemplo, abc123.fleetkey.net)",
    "nl": "FleetKey-domein (bijv. abc123.fleetkey.net)",
    "fr": "Domaine FleetKey (par exemple, abc123.fleetkey.net)",
    "it": "Dominio FleetKey (ad esempio abc123.fleetkey.net)",
    "es": "Dominio FleetKey (por ejemplo, abc123.fleetkey.net)",
    "pl": "Domena FleetKey (np. abc123.fleetkey.net)",
    "uk": "Домен FleetKey (наприклад, abc123.fleetkey.net)",
    "zh-cn": "FleetKey 域名（例如 abc123.fleetkey.net）"
  },
  "Generate Auth Link": {
    "en": "Generate Auth Link",
    "de": "Auth-Link generieren",
    "ru": "Создать ссылку для аутентификации",
    "pt": "Gerar link de autenticação",
    "nl": "Genereer een authenticatielink",
    "fr": "Générer un lien d'authentification",
    "it": "Genera collegamento di autenticazione",
    "es": "Generar enlace de autenticación",
    "pl": "Wygeneruj link uwierzytelniający",
    "uk": "Створити посилання авторизації",
    "zh-cn": "生成授权链接"
  },
  "Generate Key Pair": {
    "en": "Generate Key Pair",
    "de": "Schlüsselpaar generieren",
    "ru": "Создать пару ключей",
    "pt": "Gerar par de chaves",
    "nl": "Sleutelpaar genereren",
    "fr": "Générer une paire de clés",
    "it": "Genera coppia di chiavi",
    "es": "Generar par de claves",
    "pl": "Wygeneruj parę kluczy",
    "uk": "Створити пару ключів",
    "zh-cn": "生成密钥对"
  },
  "Location update interval in seconds (0 = disabled)": {
    "en": "Location update interval in seconds (0 = disabled)",
    "de": "Standort Update Intervall in Sekunden (0 = deaktiviert)",
    "ru": "Интервал обновления местоположения в секундах (0 = отключено)",
    "pt": "Intervalo de atualização de localização em segundos (0 = desativado)",
    "nl": "Interval voor locatie-update in seconden (0 = uitgeschakeld)",
    "fr": "Intervalle de mise à jour de l'emplacement en secondes (0 = désactivé)",
    "it": "Intervallo di aggiornamento della posizione in secondi (0 = disabilitato)",
    "es": "Intervalo de actualización de ubicación en segundos (0 = deshabilitado)",
    "pl": "Interwał aktualizacji lokalizacji w sekundach (0 = wyłączone)",
    "uk": "Інтервал оновлення місцезнаходження в секундах (0 = вимкнено)",
    "zh-cn": "位置更新间隔（以秒为单位）（0 = 禁用）"
  },
  "Options": {
    "en": "Options",
    "de": "Optionen",
    "ru": "Параметры",
    "pt": "Opções",
    "nl": "Opties",
    "fr": "Possibilités",
    "it": "Opzioni",
    "es": "Opciones",
    "pl": "Opcje",
    "uk": "Опції",
    "zh-cn": "选项"
  },
  "Public Key (copy to FleetKey.net)": {
    "en": "Public Key (copy to FleetKey.net)",
    "de": "Public Key (auf FleetKey.net kopieren)",
    "ru": "Открытый ключ (копия на FleetKey.net)",
    "pt": "Chave pública (copiar para FleetKey.net)",
    "nl": "Publieke sleutel (kopiëren naar FleetKey.net)",
    "fr": "Clé publique (copie sur FleetKey.net)",
    "it": "Chiave pubblica (copia su FleetKey.net)",
    "es": "Clave pública (copiar a FleetKey.net)",
    "pl": "Klucz publiczny (skopiuj do FleetKey.net)",
    "uk": "Відкритий ключ (копія на FleetKey.net)",
    "zh-cn": "公钥（复制到 FleetKey.net）"
  },
  "Region (Fallback)": {
    "en": "Region (Fallback, auto-detected from token)",
    "de": "Region (Fallback, wird automatisch aus Token erkannt)",
    "ru": "Регион (резервный вариант, автоматически определяется по токену)",
    "pt": "Região (Fallback, detectada automaticamente do token)",
    "nl": "Regio (Fallback, automatisch gedetecteerd door token)",
    "fr": "Région (de secours, détectée automatiquement à partir du jeton)",
    "it": "Regione (fallback, rilevata automaticamente dal token)",
    "es": "Región (alternativa, detectada automáticamente desde el token)",
    "pl": "Region (awaryjny, automatycznie wykrywany na podstawie tokena)",
    "uk": "Регіон (резервний, автоматично визначається з маркера)",
    "zh-cn": "区域（后备，从令牌自动检测）"
  },
  "Reset Login/Token Information": {
    "en": "Reset Login/Token Information",
    "de": "Login/Token Informationen zurücksetzen",
    "ru": "Сбросить информацию для входа/токена",
    "pt": "Redefinir informações de login/token",
    "nl": "Login-/tokeninformatie opnieuw instellen",
    "fr": "Réinitialiser les informations de connexion/jeton",
    "it": "Reimposta le informazioni di accesso/token",
    "es": "Restablecer información de inicio de sesión/token",
    "pl": "Zresetuj dane logowania/tokena",
    "uk": "Скинути інформацію про вхід/токен",
    "zh-cn": "重置登录/令牌信息"
  },
  "Step 1: Generate Key Pair": {
    "en": "Step 1: Generate Key Pair",
    "de": "Schritt 1: Schlüsselpaar generieren",
    "ru": "Шаг 1: Создайте пару ключей",
    "pt": "Etapa 1: gerar par de chaves",
    "nl": "Stap 1: Genereer sleutelpaar",
    "fr": "Étape 1 : Générer une paire de clés",
    "it": "Passaggio 1: generazione della coppia di chiavi",
    "es": "Paso 1: generar un par de claves",
    "pl": "Krok 1: Wygeneruj parę kluczy",
    "uk": "Крок 1: Створіть пару ключів",
    "zh-cn": "第1步：生成密钥对"
  },
  "Step 2: Tesla Developer App": {
    "en": "Step 2: Tesla Developer App",
    "de": "Schritt 2: Tesla Developer App",
    "ru": "Шаг 2. Приложение для разработчиков Tesla",
    "pt": "Etapa 2: aplicativo de desenvolvedor Tesla",
    "nl": "Stap 2: Tesla Developer-app",
    "fr": "Étape 2 : Application de développement Tesla",
    "it": "Passaggio 2: app per sviluppatori Tesla",
    "es": "Paso 2: Aplicación para desarrolladores de Tesla",
    "pl": "Krok 2: Aplikacja programistyczna Tesla",
    "uk": "Крок 2: Додаток Tesla Developer",
    "zh-cn": "第 2 步：Tesla 开发者应用程序"
  },
  "Step 3: Authentication": {
    "en": "Step 3: Authentication",
    "de": "Schritt 3: Authentifizierung",
    "ru": "Шаг 3: Аутентификация",
    "pt": "Etapa 3: Autenticação",
    "nl": "Stap 3: Authenticatie",
    "fr": "Étape 3 : Authentification",
    "it": "Passaggio 3: autenticazione",
    "es": "Paso 3: autenticación",
    "pl": "Krok 3: Uwierzytelnienie",
    "uk": "Крок 3: Автентифікація",
    "zh-cn": "第三步：身份验证"
  },
  "Step 4: Install Virtual Key": {
    "en": "Step 4: Install Virtual Key",
    "de": "Schritt 4: Virtual Key installieren",
    "ru": "Шаг 4. Установите виртуальный ключ",
    "pt": "Etapa 4: instalar a chave virtual",
    "nl": "Stap 4: Installeer virtuele sleutel",
    "fr": "Étape 4 : Installer la clé virtuelle",
    "it": "Passaggio 4: installa la chiave virtuale",
    "es": "Paso 4: instalar la clave virtual",
    "pl": "Krok 4: Zainstaluj klucz wirtualny",
    "uk": "Крок 4: Встановіть віртуальний ключ",
    "zh-cn": "第四步：安装虚拟钥匙"
  },
  "Update Settings": {
    "en": "Update Settings",
    "de": "Update Einstellungen",
    "ru": "Обновить настройки",
    "pt": "Atualizar configurações",
    "nl": "Instellingen bijwerken",
    "fr": "Mettre à jour les paramètres",
    "it": "Aggiorna impostazioni",
    "es": "Actualizar configuración",
    "pl": "Aktualizuj ustawienia",
    "uk": "Оновити налаштування",
    "zh-cn": "更新设置"
  },
  "Update interval in seconds (minimum 10)": {
    "en": "Update interval in seconds (minimum 10)",
    "de": "Update Intervall in Sekunden (Minimum 10)",
    "ru": "Интервал обновления в секундах (минимум 10)",
    "pt": "Intervalo de atualização em segundos (mínimo 10)",
    "nl": "Update-interval in seconden (minimaal 10)",
    "fr": "Intervalle de mise à jour en secondes (minimum 10)",
    "it": "Intervallo di aggiornamento in secondi (minimo 10)",
    "es": "Intervalo de actualización en segundos (mínimo 10)",
    "pl": "Interwał aktualizacji w sekundach (minimum 10)",
    "uk": "Інтервал оновлення в секундах (мінімум 10)",
    "zh-cn": "更新间隔（以秒为单位）（最小 10）"
  },
  "Update interval while driving in seconds (0 = disabled)": {
    "en": "Update interval while driving in seconds (0 = disabled)",
    "de": "Update Intervall während der Fahrt in Sekunden (0 = deaktiviert)",
    "ru": "Интервал обновления во время движения в секундах (0 = отключено)",
    "pt": "Intervalo de atualização durante a condução em segundos (0 = desativado)",
    "nl": "Update-interval tijdens het rijden in seconden (0 = uitgeschakeld)",
    "fr": "Intervalle de mise à jour pendant la conduite en secondes (0 = désactivé)",
    "it": "Intervallo di aggiornamento durante la guida in secondi (0 = disabilitato)",
    "es": "Intervalo de actualización mientras se conduce en segundos (0 = deshabilitado)",
    "pl": "Częstotliwość aktualizacji podczas jazdy w sekundach (0 = wyłączone)",
    "uk": "Інтервал оновлення під час руху в секундах (0 = вимкнено)",
    "zh-cn": "驾驶时的更新间隔（以秒为单位）（0 = 禁用）"
  },
  "Wake up vehicle for each update (prevents sleep to save battery)": {
    "en": "Wake up vehicle for each update (prevents sleep to save battery)",
    "de": "Fahrzeug für jedes Update aufwecken (verhindert Schlafmodus zum Batterie sparen)",
    "ru": "Пробуждение автомобиля для каждого обновления (предотвращает сон для экономии заряда батареи)",
    "pt": "Acorde o veículo para cada atualização (evita o sono para economizar bateria)",
    "nl": "Maak het voertuig wakker voor elke update (voorkomt slaap om de batterij te sparen)",
    "fr": "Réveiller le véhicule à chaque mise à jour (empêche la mise en veille pour économiser la batterie)",
    "it": "Riattiva il veicolo per ogni aggiornamento (impedisce la sospensione per risparmiare batteria)",
    "es": "Activa el vehículo para cada actualización (evita el modo de suspensión para ahorrar batería)",
    "pl": "Obudź pojazd przy każdej aktualizacji (zapobiega uśpieniu, aby oszczędzać baterię)",
    "uk": "Виводити транспортний засіб з режиму сну для кожного оновлення (запобігає режиму сну для економії заряду акумулятора)",
    "zh-cn": "每次更新时唤醒车辆（防止休眠以节省电量）"
  },
  "step1_instruction1": {
    "en": "Click \"Generate Key Pair\" below to create an EC key pair (prime256v1)",
    "de": "Klicke unten auf \"Schlüsselpaar generieren\" um ein EC-Schlüsselpaar (prime256v1) zu erstellen",
    "ru": "Нажмите «Создать пару ключей» ниже, чтобы создать пару ключей EC (prime256v1).",
    "pt": "Clique em \"Gerar par de chaves\" abaixo para criar um par de chaves EC (prime256v1)",
    "nl": "Klik hieronder op \"Sleutelpaar genereren\" om een ​​EC-sleutelpaar aan te maken (prime256v1)",
    "fr": "Cliquez sur \"Générer une paire de clés\" ci-dessous pour créer une paire de clés EC (prime256v1)",
    "it": "Fai clic su \"Genera coppia di chiavi\" di seguito per creare una coppia di chiavi EC (prime256v1)",
    "es": "Haga clic en \"Generar par de claves\" a continuación para crear un par de claves EC (prime256v1)",
    "pl": "Kliknij „Generuj parę kluczy” poniżej, aby utworzyć parę kluczy EC (prime256v1)",
    "uk": "Натисніть «Створити пару ключів» нижче, щоб створити пару ключів EC (prime256v1)",
    "zh-cn": "点击下方“生成密钥对”，创建EC密钥对（prime256v1）"
  },
  "step1_instruction2": {
    "en": "Copy the Public Key and go to <a href=\"https://fleetkey.net\" target=\"_blank\">fleetkey.net</a> - create an account and get your subdomain (e.g. abc123.fleetkey.net)",
    "de": "Kopiere den Public Key und gehe zu <a href=\"https://fleetkey.net\" target=\"_blank\">fleetkey.net</a> - erstelle ein Konto und erhalte deine Subdomain (z.B. abc123.fleetkey.net)",
    "ru": "Скопируйте открытый ключ и перейдите на сайт <a href=\"https://fleetkey.net\" target=\"_blank\">fleetkey.net</a> — создайте учетную запись и получите свой поддомен (например, abc123.fleetkey.net).",
    "pt": "Copie a chave pública e acesse <a href=\"https://fleetkey.net\" target=\"_blank\">fleetkey.net</a> - crie uma conta e obtenha seu subdomínio (por exemplo, abc123.fleetkey.net)",
    "nl": "Kopieer de openbare sleutel en ga naar <a href=\"https://fleetkey.net\" target=\"_blank\">fleetkey.net</a> - maak een account aan en verkrijg uw subdomein (bijvoorbeeld abc123.fleetkey.net)",
    "fr": "Copiez la clé publique et accédez à <a href=\"https://fleetkey.net\" target=\"_blank\">fleetkey.net</a> - créez un compte et obtenez votre sous-domaine (par exemple abc123.fleetkey.net)",
    "it": "Copia la chiave pubblica e vai su <a href=\"https://fleetkey.net\" target=\"_blank\">fleetkey.net</a> - crea un account e ottieni il tuo sottodominio (ad esempio abc123.fleetkey.net)",
    "es": "Copie la clave pública y vaya a <a href=\"https://fleetkey.net\" target=\"_blank\">fleetkey.net</a>; cree una cuenta y obtenga su subdominio (por ejemplo, abc123.fleetkey.net).",
    "pl": "Skopiuj klucz publiczny i przejdź do <a href=\"https://fleetkey.net\" target=\"_blank\">fleetkey.net</a> - utwórz konto i uzyskaj subdomenę (np. abc123.fleetkey.net)",
    "uk": "Скопіюйте відкритий ключ і перейдіть на <a href=\"https://fleetkey.net\" target=\"_blank\">fleetkey.net</a> - створіть обліковий запис і отримайте свій субдомен (наприклад, abc123.fleetkey.net)",
    "zh-cn": "复制公钥并转到 <a href=\"https://fleetkey.net\" target=\"_blank\">fleetkey.net</a> - 创建帐户并获取您的子域（例如 abc123.fleetkey.net）"
  },
  "step1_instruction3": {
    "en": "Upload the Public Key to your FleetKey.net account. Tesla will download the key from there during registration.",
    "de": "Lade den Public Key in dein FleetKey.net Konto hoch. Tesla lädt den Key von dort während der Registrierung herunter.",
    "ru": "Загрузите открытый ключ в свою учетную запись FleetKey.net. Tesla скачает оттуда ключ во время регистрации.",
    "pt": "Carregue a chave pública para sua conta FleetKey.net. A Tesla fará o download da chave durante o registro.",
    "nl": "Upload de openbare sleutel naar uw FleetKey.net-account. Tesla zal de sleutel daar downloaden tijdens de registratie.",
    "fr": "Téléchargez la clé publique sur votre compte FleetKey.net. Tesla téléchargera la clé à partir de là lors de l'inscription.",
    "it": "Carica la chiave pubblica sul tuo account FleetKey.net. Tesla scaricherà la chiave da lì durante la registrazione.",
    "es": "Cargue la clave pública a su cuenta FleetKey.net. Tesla descargará la clave desde allí durante el registro.",
    "pl": "Prześlij klucz publiczny na swoje konto FleetKey.net. Tesla pobierze stamtąd klucz podczas rejestracji.",
    "uk": "Завантажте відкритий ключ у свій обліковий запис FleetKey.net. Tesla завантажить ключ звідти під час реєстрації.",
    "zh-cn": "将公钥上传到您的 FleetKey.net 帐户。特斯拉将在注册过程中从那里下载密钥。"
  },
  "step2_instruction1": {
    "en": "Create a Fleet API Application at ",
    "de": "Erstelle eine Fleet API Application auf ",
    "ru": "Создайте приложение Fleet API на странице",
    "pt": "Crie um aplicativo Fleet API em",
    "nl": "Maak een Fleet API-applicatie op",
    "fr": "Créez une application API de flotte sur",
    "it": "Crea un'applicazione API Fleet su",
    "es": "Cree una aplicación API de flota en",
    "pl": "Utwórz aplikację Fleet API pod adresem",
    "uk": "Створіть додаток Fleet API за адресою",
    "zh-cn": "创建车队 API 应用程序："
  },
  "step2_instruction2": {
    "en": "Origin: https://&lt;your-subdomain&gt;.fleetkey.net (your full FleetKey subdomain, e.g. https://abc123.fleetkey.net)",
    "de": "Origin: https://&lt;deine-subdomain&gt;.fleetkey.net (deine volle FleetKey Subdomain, z.B. https://abc123.fleetkey.net)",
    "ru": "Происхождение: https://<ваш-субдомен>.fleetkey.net (ваш полный субдомен FleetKey, например https://abc123.fleetkey.net)",
    "pt": "Origem: https://<seu-subdomínio>.fleetkey.net (seu subdomínio FleetKey completo, por exemplo, https://abc123.fleetkey.net)",
    "nl": "Herkomst: https://<uw-subdomein>.fleetkey.net (uw volledige FleetKey-subdomein, bijvoorbeeld https://abc123.fleetkey.net)",
    "fr": "Origine : https://<votre-sous-domaine>.fleetkey.net (votre sous-domaine FleetKey complet, par exemple https://abc123.fleetkey.net)",
    "it": "Origine: https://<tuo-sottodominio>.fleetkey.net (il tuo sottodominio FleetKey completo, ad esempio https://abc123.fleetkey.net)",
    "es": "Origen: https://<su-subdominio>.fleetkey.net (su subdominio FleetKey completo, por ejemplo, https://abc123.fleetkey.net)",
    "pl": "Pochodzenie: https://<twoja-subdomena>.fleetkey.net (Twoja pełna subdomena FleetKey, np. https://abc123.fleetkey.net)",
    "uk": "Походження: https://<your-subdomain>.fleetkey.net (ваш повний субдомен FleetKey, наприклад https://abc123.fleetkey.net)",
    "zh-cn": "来源：https://<your-subdomain>.fleetkey.net（您的完整 FleetKey 子域，例如 https://abc123.fleetkey.net）"
  },
  "step2_instruction3": {
    "en": "Redirect URL: https://auth.tesla.com/void/callback",
    "de": "Redirect URL: https://auth.tesla.com/void/callback",
    "ru": "URL-адрес перенаправления: https://auth.tesla.com/void/callback",
    "pt": "URL de redirecionamento: https://auth.tesla.com/void/callback",
    "nl": "Omleidings-URL: https://auth.tesla.com/void/callback",
    "fr": "URL de redirection : https://auth.tesla.com/void/callback",
    "it": "URL di reindirizzamento: https://auth.tesla.com/void/callback",
    "es": "URL de redireccionamiento: https://auth.tesla.com/void/callback",
    "pl": "Adres URL przekierowania: https://auth.tesla.com/void/callback",
    "uk": "URL-адреса перенаправлення: https://auth.tesla.com/void/callback",
    "zh-cn": "重定向网址：https://auth.tesla.com/void/callback"
  },
  "step2_instruction4": {
    "en": "Copy Client ID and Client Secret from the created app and enter them below together with your FleetKey domain",
    "de": "Kopiere Client ID und Client Secret von der erstellten App und trage sie unten zusammen mit deiner FleetKey Domain ein",
    "ru": "Скопируйте идентификатор клиента и секрет клиента из созданного приложения и введите их ниже вместе с вашим доменом FleetKey.",
    "pt": "Copie o ID do cliente e o segredo do cliente do aplicativo criado e insira-os abaixo junto com seu domínio FleetKey",
    "nl": "Kopieer Client ID en Client Secret uit de gemaakte app en voer deze hieronder in samen met uw FleetKey-domein",
    "fr": "Copiez l'ID client et le secret client de l'application créée et saisissez-les ci-dessous avec votre domaine FleetKey.",
    "it": "Copia l'ID cliente e il segreto cliente dall'app creata e inseriscili di seguito insieme al tuo dominio FleetKey",
    "es": "Copie el ID de cliente y el secreto de cliente de la aplicación creada e introdúzcalos a continuación junto con su dominio FleetKey",
    "pl": "Skopiuj identyfikator klienta i sekret klienta z utworzonej aplikacji i wprowadź je poniżej wraz z domeną FleetKey",
    "uk": "Скопіюйте ідентифікатор клієнта та секрет клієнта зі створеної програми та введіть їх нижче разом із вашим доменом FleetKey",
    "zh-cn": "从创建的应用程序中复制客户端 ID 和客户端密钥，并在下面与您的 FleetKey 域一起输入"
  },
  "step3_instruction1": {
    "en": "Click \"Generate Auth Link\" - a new browser tab opens with the Tesla login page",
    "de": "Klicke auf \"Auth-Link generieren\" - ein neuer Browser-Tab öffnet sich mit der Tesla-Login-Seite",
    "ru": "Нажмите «Создать ссылку для аутентификации» — откроется новая вкладка браузера со страницей входа в Tesla.",
    "pt": "Clique em \"Gerar link de autenticação\" - uma nova guia do navegador é aberta com a página de login do Tesla",
    "nl": "Klik op \"Auth link genereren\" - er wordt een nieuw browsertabblad geopend met de Tesla-inlogpagina",
    "fr": "Cliquez sur \"Générer un lien d'authentification\" - un nouvel onglet de navigateur s'ouvre avec la page de connexion Tesla",
    "it": "Fai clic su \"Genera collegamento di autenticazione\": si apre una nuova scheda del browser con la pagina di accesso di Tesla",
    "es": "Haga clic en \"Generar enlace de autenticación\": se abre una nueva pestaña del navegador con la página de inicio de sesión de Tesla.",
    "pl": "Kliknij „Generuj link uwierzytelniający” – otworzy się nowa karta przeglądarki ze stroną logowania Tesli",
    "uk": "Натисніть «Generate Auth Link» — відкриється нова вкладка браузера зі сторінкою входу Tesla",
    "zh-cn": "单击“生成身份验证链接” - 将打开一个新的浏览器选项卡，其中包含 Tesla 登录页面"
  },
  "step3_instruction2": {
    "en": "Log in with your Tesla account and authorize the app",
    "de": "Melde dich mit deinem Tesla-Konto an und autorisiere die App",
    "ru": "Войдите в свою учетную запись Tesla и авторизуйте приложение.",
    "pt": "Faça login com sua conta Tesla e autorize o aplicativo",
    "nl": "Log in met uw Tesla-account en autoriseer de app",
    "fr": "Connectez-vous avec votre compte Tesla et autorisez l'application",
    "it": "Accedi con il tuo account Tesla e autorizza l'app",
    "es": "Inicie sesión con su cuenta Tesla y autorice la aplicación",
    "pl": "Zaloguj się na swoje konto Tesla i autoryzuj aplikację",
    "uk": "Увійдіть за допомогою свого облікового запису Tesla та авторизуйте додаток",
    "zh-cn": "使用您的特斯拉帐户登录并授权该应用程序"
  },
  "step3_instruction3": {
    "en": "After login you will see \"Page Not Found\" - this is expected! Copy the complete URL from the browser address bar",
    "de": "Nach dem Login erscheint \"Page Not Found\" - das ist korrekt! Kopiere die komplette URL aus der Browser-Adresszeile",
    "ru": "После входа в систему вы увидите «Страница не найдена» — это ожидаемо! Скопируйте полный URL-адрес из адресной строки браузера.",
    "pt": "Após o login você verá \"Página não encontrada\" - isso é esperado! Copie o URL completo da barra de endereço do navegador",
    "nl": "Na het inloggen ziet u \"Pagina niet gevonden\" - dit wordt verwacht! Kopieer de volledige URL uit de adresbalk van de browser",
    "fr": "Après la connexion, vous verrez « Page non trouvée » – c'est normal ! Copiez l'URL complète depuis la barre d'adresse du navigateur",
    "it": "Dopo l'accesso vedrai \"Pagina non trovata\" - questo è previsto! Copia l'URL completo dalla barra degli indirizzi del browser",
    "es": "Después de iniciar sesión, verá \"Página no encontrada\". ¡Esto es lo esperado! Copie la URL completa desde la barra de direcciones del navegador",
    "pl": "Po zalogowaniu zobaczysz komunikat „Nie znaleziono strony” – tego można się spodziewać! Skopiuj cały adres URL z paska adresu przeglądarki",
    "uk": "Після входу ви побачите \"Сторінку не знайдено\" - це очікувано! Скопіюйте повну URL-адресу з адресного рядка браузера",
    "zh-cn": "登录后，您将看到“页面未找到”——这是预期的！从浏览器地址栏中复制完整的 URL"
  },
  "step3_instruction4": {
    "en": "Paste the URL into the field below and click \"Save and close\"",
    "de": "Füge die URL in das Feld unten ein und klicke auf \"Speichern und schließen\"",
    "ru": "Вставьте URL-адрес в поле ниже и нажмите «Сохранить и закрыть».",
    "pt": "Cole o URL no campo abaixo e clique em \"Salvar e fechar\"",
    "nl": "Plak de URL in het onderstaande veld en klik op \"Opslaan en sluiten\"",
    "fr": "Collez l'URL dans le champ ci-dessous et cliquez sur \"Enregistrer et fermer\".",
    "it": "Incolla l'URL nel campo sottostante e fai clic su \"Salva e chiudi\"",
    "es": "Pegue la URL en el campo siguiente y haga clic en \"Guardar y cerrar\".",
    "pl": "Wklej adres URL w polu poniżej i kliknij „Zapisz i zamknij”",
    "uk": "Вставте URL-адресу в поле нижче та натисніть «Зберегти та закрити»",
    "zh-cn": "将 URL 粘贴到下面的字段中，然后单击“保存并关闭”"
  },
  "step3_warning": {
    "en": "Never share this URL with anyone! It grants access to your Tesla account.",
    "de": "Teile diese URL niemals mit anderen Personen! Sie erlaubt Zugang zu deinem Tesla-Konto.",
    "ru": "Никогда никому не передавайте этот URL! Он предоставляет доступ к вашей учетной записи Tesla.",
    "pt": "Nunca compartilhe este URL com ninguém! Concede acesso à sua conta Tesla.",
    "nl": "Deel deze URL nooit met iemand! Het geeft toegang tot uw Tesla-account.",
    "fr": "Ne partagez jamais cette URL avec qui que ce soit ! Il donne accès à votre compte Tesla.",
    "it": "Non condividere mai questo URL con nessuno! Concede l'accesso al tuo account Tesla.",
    "es": "¡Nunca compartas esta URL con nadie! Otorga acceso a su cuenta Tesla.",
    "pl": "Nigdy nie udostępniaj nikomu tego adresu URL! Zapewnia dostęp do Twojego konta Tesla.",
    "uk": "Ніколи нікому не діліться цією URL-адресою! Він надає доступ до вашого облікового запису Tesla.",
    "zh-cn": "切勿与任何人分享此 URL！它授予您访问您的 Tesla 帐户的权限。"
  },
  "step4_description": {
    "en": "The Virtual Key is required to send commands to your vehicle (lock/unlock, climate, charging, etc.). Without it, you can only read vehicle data. You can do this step after the adapter is running.",
    "de": "Der Virtual Key wird benötigt um Kommandos an dein Fahrzeug zu senden (Ver-/Entriegeln, Klima, Laden, etc.). Ohne ihn kannst du nur Fahrzeugdaten lesen. Dieser Schritt kann nach dem Start des Adapters durchgeführt werden.",
    "ru": "Виртуальный ключ необходим для отправки команд вашему автомобилю (запирание/разблокировка, климат, зарядка и т. д.). Без него вы сможете только прочитать данные автомобиля. Этот шаг можно выполнить после запуска адаптера.",
    "pt": "A Chave Virtual é necessária para enviar comandos ao seu veículo (trancar/destrancar, climatização, carregamento, etc.). Sem ele, você só poderá ler os dados do veículo. Você pode executar esta etapa depois que o adaptador estiver em execução.",
    "nl": "De virtuele sleutel is vereist om opdrachten naar uw voertuig te sturen (vergrendelen/ontgrendelen, klimaatregeling, opladen, enz.). Zonder dit kunt u alleen voertuiggegevens uitlezen. U kunt deze stap uitvoeren nadat de adapter actief is.",
    "fr": "La Clé Virtuelle est nécessaire pour envoyer des commandes à votre véhicule (verrouillage/déverrouillage, climatisation, recharge…). Sans cela, vous ne pouvez lire que les données du véhicule. Vous pouvez effectuer cette étape une fois l'adaptateur en cours d'exécution.",
    "it": "La Chiave Virtuale è necessaria per inviare comandi al tuo veicolo (bloccaggio/sbloccaggio, clima, ricarica, ecc.). Senza di esso, puoi solo leggere i dati del veicolo. Puoi eseguire questo passaggio dopo che l'adattatore è in esecuzione.",
    "es": "La llave virtual es necesaria para enviar comandos a su vehículo (bloqueo/desbloqueo, clima, carga, etc.). Sin él, sólo puedes leer los datos del vehículo. Puede realizar este paso después de que el adaptador se esté ejecutando.",
    "pl": "Klucz wirtualny jest wymagany do wysyłania poleceń do Twojego pojazdu (zablokowanie/odblokowanie, klimatyzacja, ładowanie itp.). Bez niego można jedynie odczytać dane pojazdu. Tę czynność można wykonać po uruchomieniu adaptera.",
    "uk": "Віртуальний ключ потрібен для надсилання команд вашому автомобілю (блокування/розблокування, клімат, зарядка тощо). Без нього можна лише читати дані транспортного засобу. Цей крок можна виконати після того, як адаптер запрацює.",
    "zh-cn": "需要虚拟钥匙才能向您的车辆发送命令（锁定/解锁、气候、充电等）。没有它，您只能读取车辆数据。您可以在适配器运行后执行此步骤。"
  },
  "step4_instruction1": {
    "en": "Open the URL below on your phone in the Tesla App, or scan the QR code with your phone camera",
    "de": "Öffne die URL unten auf deinem Handy in der Tesla App, oder scanne den QR-Code mit der Handy-Kamera",
    "ru": "Откройте URL-адрес ниже на своем телефоне в приложении Tesla или отсканируйте QR-код с помощью камеры телефона.",
    "pt": "Abra o URL abaixo no seu telefone na aplicação Tesla ou leia o código QR com a câmara do seu telefone",
    "nl": "Open de onderstaande URL op uw telefoon in de Tesla-app of scan de QR-code met de camera van uw telefoon",
    "fr": "Ouvrez l'URL ci-dessous sur votre téléphone dans l'application Tesla ou scannez le code QR avec l'appareil photo de votre téléphone.",
    "it": "Apri l'URL riportato di seguito sul telefono nell'app Tesla oppure scansiona il codice QR con la fotocamera del telefono",
    "es": "Abra la siguiente URL en su teléfono en la aplicación Tesla o escanee el código QR con la cámara de su teléfono",
    "pl": "Otwórz poniższy adres URL na swoim telefonie w aplikacji Tesla lub zeskanuj kod QR aparatem w telefonie",
    "uk": "Відкрийте URL-адресу нижче на своєму телефоні в додатку Tesla або відскануйте QR-код за допомогою камери телефону",
    "zh-cn": "在手机上的 Tesla App 中打开以下网址，或使用手机摄像头扫描二维码"
  },
  "step4_instruction2": {
    "en": "The Tesla App will ask you to confirm adding a \"third-party key\"",
    "de": "Die Tesla App fragt dich ob du einen \"Drittanbieter-Schlüssel\" hinzufügen möchtest",
    "ru": "Приложение Tesla попросит вас подтвердить добавление «стороннего ключа».",
    "pt": "O aplicativo Tesla solicitará que você confirme a adição de uma “chave de terceiros”",
    "nl": "De Tesla-app vraagt ​​u om het toevoegen van een \"sleutel van derden\" te bevestigen",
    "fr": "L'application Tesla vous demandera de confirmer l'ajout d'une « clé tierce »",
    "it": "L'app Tesla ti chiederà di confermare l'aggiunta di una \"chiave di terze parti\"",
    "es": "La aplicación Tesla le pedirá que confirme agregar una \"clave de terceros\"",
    "pl": "Aplikacja Tesla poprosi Cię o potwierdzenie dodania „klucza innej firmy”",
    "uk": "Додаток Tesla попросить вас підтвердити додавання «стороннього ключа»",
    "zh-cn": "Tesla 应用程序会要求您确认添加“第三方密钥”"
  },
  "step4_instruction3": {
    "en": "Go to your vehicle and hold your key card to the center console to confirm the installation",
    "de": "Gehe zu deinem Fahrzeug und halte deine Schlüsselkarte an die Mittelkonsole um die Installation zu bestätigen",
    "ru": "Подойдите к своему автомобилю и поднесите ключ-карту к центральной консоли, чтобы подтвердить установку.",
    "pt": "Vá até o seu veículo e segure seu cartão-chave no console central para confirmar a instalação",
    "nl": "Ga naar uw auto en houd uw sleutelkaart tegen de middenconsole om de installatie te bevestigen",
    "fr": "Accédez à votre véhicule et tenez votre carte-clé près de la console centrale pour confirmer l'installation",
    "it": "Vai al tuo veicolo e avvicina la chiave magnetica alla console centrale per confermare l'installazione",
    "es": "Vaya a su vehículo y acerque su tarjeta de acceso a la consola central para confirmar la instalación.",
    "pl": "Podejdź do pojazdu i przyłóż kartę kluczykową do konsoli środkowej, aby potwierdzić instalację",
    "uk": "Підійдіть до свого автомобіля та піднесіть картку-ключ до центральної консолі, щоб підтвердити встановлення",
    "zh-cn": "前往您的车辆并将钥匙卡放在中控台上以确认安装"
  },
  "step4_qr_hint": {
    "en": "Scan this QR code with your phone to open the URL directly in the Tesla App",
    "de": "Scanne diesen QR-Code mit deinem Handy um die URL direkt in der Tesla App zu öffnen",
    "ru": "Отсканируйте этот QR-код своим телефоном, чтобы открыть URL-адрес прямо в приложении Tesla.",
    "pt": "Digitalize este código QR com o seu telefone para abrir o URL diretamente na aplicação Tesla",
    "nl": "Scan deze QR-code met uw telefoon om de URL rechtstreeks in de Tesla-app te openen",
    "fr": "Scannez ce code QR avec votre téléphone pour ouvrir l'URL directement dans l'application Tesla",
    "it": "Scansiona questo codice QR con il tuo telefono per aprire l'URL direttamente nell'app Tesla",
    "es": "Escanee este código QR con su teléfono para abrir la URL directamente en la aplicación Tesla",
    "pl": "Zeskanuj ten kod QR telefonem, aby otworzyć adres URL bezpośrednio w aplikacji Tesla",
    "uk": "Відскануйте цей QR-код телефоном, щоб відкрити URL-адресу безпосередньо в додатку Tesla",
    "zh-cn": "用手机扫描此二维码可直接在 Tesla App 中打开网址"
  },
  "step4_url_label": {
    "en": "Virtual Key URL:",
    "de": "Virtual Key URL:",
    "ru": "URL-адрес виртуального ключа:",
    "pt": "URL da chave virtual:",
    "nl": "Virtuele sleutel-URL:",
    "fr": "URL de la clé virtuelle :",
    "it": "URL della chiave virtuale:",
    "es": "URL de clave virtual:",
    "pl": "Adres URL klucza wirtualnego:",
    "uk": "URL віртуального ключа:",
    "zh-cn": "虚拟密钥网址："
  },
  "tesla-motors adapter settings": {
    "en": "Adapter settings for tesla-motors",
    "de": "Adaptereinstellungen für tesla-motors",
    "ru": "Настройки адаптера для моторов Tesla",
    "pt": "Configurações do adaptador para motores tesla",
    "nl": "Adapterinstellingen voor Tesla-motoren",
    "fr": "Paramètres de l'adaptateur pour les moteurs Tesla",
    "it": "Impostazioni dell'adattatore per motori Tesla",
    "es": "Configuración del adaptador para motores Tesla.",
    "pl": "Ustawienia adaptera dla silników Tesli",
    "uk": "Налаштування адаптера для tesla-motors",
    "zh-cn": "特斯拉电机的适配器设置"
  },
  "telemetry_tab_general": {
    "en": "Adapter / Fleet API",
    "de": "Adapter / Fleet API",
    "ru": "Адаптер / Fleet API",
    "pt": "Adaptador / Fleet API",
    "nl": "Adapter / Fleet API",
    "fr": "Adaptateur / Fleet API",
    "it": "Adattatore / Fleet API",
    "es": "Adaptador / Fleet API",
    "pl": "Adapter / Fleet API",
    "uk": "Адаптер / Fleet API",
    "zh-cn": "适配器 / Fleet API"
  },
  "telemetry_tab_fields": {
    "en": "Fleet Telemetry fields",
    "de": "Fleet-Telemetry-Felder",
    "ru": "Поля Fleet Telemetry",
    "pt": "Campos de Fleet Telemetry",
    "nl": "Fleet Telemetry-velden",
    "fr": "Champs Fleet Telemetry",
    "it": "Campi Fleet Telemetry",
    "es": "Campos de Fleet Telemetry",
    "pl": "Pola Fleet Telemetry",
    "uk": "Поля Fleet Telemetry",
    "zh-cn": "Fleet Telemetry 字段"
  },
  "telemetry_bridge_title": {
    "en": "Fleet Telemetry (MQTT bridge)",
    "de": "Fleet Telemetry (MQTT-Bridge)",
    "ru": "Fleet Telemetry (MQTT-мост)",
    "pt": "Fleet Telemetry (ponte MQTT)",
    "nl": "Fleet Telemetry (MQTT-bridge)",
    "fr": "Fleet Telemetry (pont MQTT)",
    "it": "Fleet Telemetry (bridge MQTT)",
    "es": "Fleet Telemetry (puente MQTT)",
    "pl": "Fleet Telemetry (most MQTT)",
    "uk": "Fleet Telemetry (MQTT-міст)",
    "zh-cn": "Fleet Telemetry（MQTT 桥接）"
  },
  "telemetry_bridge_description": {
    "en": "Configure a local vehicle-command proxy plus an MQTT-fed Fleet Telemetry server. The adapter will then update the existing Tesla states from MQTT instead of using regular <code>vehicle_data</code> polling.",
    "de": "Konfiguriert einen lokalen vehicle-command-Proxy und einen MQTT-basierten Fleet-Telemetry-Server. Der Adapter aktualisiert danach die vorhandenen Tesla-Zustände per MQTT statt über reguläres <code>vehicle_data</code>-Polling.",
    "ru": "Настройте локальный прокси vehicle-command и сервер Fleet Telemetry, передающий данные в MQTT. Затем адаптер будет обновлять существующие состояния Tesla из MQTT вместо регулярного опроса <code>vehicle_data</code>.",
    "pt": "Configure um proxy vehicle-command local e um servidor Fleet Telemetry alimentado por MQTT. O adaptador atualizará os estados Tesla existentes via MQTT em vez de usar a sondagem regular de <code>vehicle_data</code>.",
    "nl": "Configureer een lokale vehicle-command-proxy en een Fleet Telemetry-server die via MQTT publiceert. De adapter werkt daarna de bestaande Tesla-statussen bij vanuit MQTT in plaats van via reguliere <code>vehicle_data</code>-polling.",
    "fr": "Configurez un proxy vehicle-command local ainsi qu’un serveur Fleet Telemetry alimenté par MQTT. L’adaptateur mettra ensuite à jour les états Tesla existants depuis MQTT au lieu d’utiliser l’interrogation régulière <code>vehicle_data</code>.",
    "it": "Configura un proxy vehicle-command locale e un server Fleet Telemetry alimentato da MQTT. L’adattatore aggiornerà quindi gli stati Tesla esistenti tramite MQTT invece di usare il polling regolare di <code>vehicle_data</code>.",
    "es": "Configure un proxy vehicle-command local y un servidor Fleet Telemetry alimentado por MQTT. El adaptador actualizará entonces los estados Tesla existentes desde MQTT en lugar de usar el sondeo regular de <code>vehicle_data</code>.",
    "pl": "Skonfiguruj lokalny proxy vehicle-command oraz serwer Fleet Telemetry publikujący do MQTT. Adapter będzie następnie aktualizował istniejące stany Tesla z MQTT zamiast używać regularnego odpytywania <code>vehicle_data</code>.",
    "uk": "Налаштуйте локальний проксі vehicle-command і сервер Fleet Telemetry, що надсилає дані через MQTT. Після цього адаптер оновлюватиме наявні стани Tesla з MQTT замість регулярного опитування <code>vehicle_data</code>.",
    "zh-cn": "配置本地 vehicle-command 代理和基于 MQTT 的 Fleet Telemetry 服务器。随后适配器将从 MQTT 更新现有 Tesla 状态，而不是定期轮询 <code>vehicle_data</code>。"
  },
  "telemetry_enabled": {
    "en": "Enable Fleet Telemetry mode",
    "de": "Fleet-Telemetry-Modus aktivieren",
    "ru": "Включить режим Fleet Telemetry",
    "pt": "Ativar modo Fleet Telemetry",
    "nl": "Fleet Telemetry-modus inschakelen",
    "fr": "Activer le mode Fleet Telemetry",
    "it": "Attiva modalità Fleet Telemetry",
    "es": "Activar modo Fleet Telemetry",
    "pl": "Włącz tryb Fleet Telemetry",
    "uk": "Увімкнути режим Fleet Telemetry",
    "zh-cn": "启用 Fleet Telemetry 模式"
  },
  "telemetry_proxy_url": {
    "en": "Vehicle-command proxy URL",
    "de": "vehicle-command-Proxy-URL",
    "ru": "URL прокси vehicle-command",
    "pt": "URL do proxy vehicle-command",
    "nl": "vehicle-command-proxy-URL",
    "fr": "URL du proxy vehicle-command",
    "it": "URL proxy vehicle-command",
    "es": "URL del proxy vehicle-command",
    "pl": "Adres URL proxy vehicle-command",
    "uk": "URL проксі vehicle-command",
    "zh-cn": "vehicle-command 代理 URL"
  },
  "telemetry_proxy_allow_insecure": {
    "en": "Allow self-signed proxy TLS certificate",
    "de": "Selbstsigniertes Proxy-TLS-Zertifikat erlauben",
    "ru": "Разрешить самоподписанный TLS-сертификат прокси",
    "pt": "Permitir certificado TLS de proxy autoassinado",
    "nl": "Zelfondertekend proxy-TLS-certificaat toestaan",
    "fr": "Autoriser le certificat TLS proxy auto-signé",
    "it": "Consenti certificato TLS proxy autofirmato",
    "es": "Permitir certificado TLS de proxy autofirmado",
    "pl": "Zezwól na samopodpisany certyfikat TLS proxy",
    "uk": "Дозволити самопідписаний TLS-сертифікат проксі",
    "zh-cn": "允许自签名代理 TLS 证书"
  },
  "telemetry_server_host": {
    "en": "Telemetry server hostname",
    "de": "Telemetry-Server-Hostname",
    "ru": "Имя хоста сервера Telemetry",
    "pt": "Nome do host do servidor Telemetry",
    "nl": "Hostnaam van Telemetry-server",
    "fr": "Nom d’hôte du serveur Telemetry",
    "it": "Nome host del server Telemetry",
    "es": "Nombre de host del servidor Telemetry",
    "pl": "Nazwa hosta serwera Telemetry",
    "uk": "Ім’я хоста сервера Telemetry",
    "zh-cn": "Telemetry 服务器主机名"
  },
  "telemetry_server_port": {
    "en": "Telemetry server port",
    "de": "Telemetry-Server-Port",
    "ru": "Порт сервера Telemetry",
    "pt": "Porta do servidor Telemetry",
    "nl": "Poort van Telemetry-server",
    "fr": "Port du serveur Telemetry",
    "it": "Porta del server Telemetry",
    "es": "Puerto del servidor Telemetry",
    "pl": "Port serwera Telemetry",
    "uk": "Порт сервера Telemetry",
    "zh-cn": "Telemetry 服务器端口"
  },
  "telemetry_fallback_poll": {
    "en": "Keep polling fallback for unsupported endpoints",
    "de": "Polling-Fallback für nicht unterstützte Endpunkte beibehalten",
    "ru": "Оставить резервный опрос для неподдерживаемых конечных точек",
    "pt": "Manter fallback de sondagem para endpoints não suportados",
    "nl": "Polling-fallback behouden voor niet-ondersteunde endpoints",
    "fr": "Conserver le repli par interrogation pour les points de terminaison non pris en charge",
    "it": "Mantieni fallback di polling per endpoint non supportati",
    "es": "Mantener sondeo de respaldo para endpoints no compatibles",
    "pl": "Zachowaj awaryjne odpytywanie dla nieobsługiwanych endpointów",
    "uk": "Залишити резервне опитування для непідтримуваних кінцевих точок",
    "zh-cn": "为不支持的端点保留轮询回退"
  },
  "telemetry_server_ca": {
    "en": "Telemetry server CA / full chain PEM",
    "de": "Telemetry-Server-CA / vollständige Zertifikatskette (PEM)",
    "ru": "CA сервера Telemetry / полная цепочка PEM",
    "pt": "CA do servidor Telemetry / cadeia PEM completa",
    "nl": "Telemetry-server-CA / volledige PEM-keten",
    "fr": "CA du serveur Telemetry / chaîne PEM complète",
    "it": "CA server Telemetry / catena PEM completa",
    "es": "CA del servidor Telemetry / cadena PEM completa",
    "pl": "CA serwera Telemetry / pełny łańcuch PEM",
    "uk": "CA сервера Telemetry / повний ланцюжок PEM",
    "zh-cn": "Telemetry 服务器 CA / 完整 PEM 证书链"
  },
  "telemetry_mqtt_broker": {
    "en": "MQTT broker",
    "de": "MQTT-Broker",
    "ru": "MQTT-брокер",
    "pt": "Broker MQTT",
    "nl": "MQTT-broker",
    "fr": "Broker MQTT",
    "it": "Broker MQTT",
    "es": "Broker MQTT",
    "pl": "Broker MQTT",
    "uk": "MQTT-брокер",
    "zh-cn": "MQTT 代理"
  },
  "telemetry_mqtt_topic_base": {
    "en": "MQTT topic base",
    "de": "MQTT-Topic-Basis",
    "ru": "Базовый MQTT-топик",
    "pt": "Base do tópico MQTT",
    "nl": "MQTT-topicbasis",
    "fr": "Base du topic MQTT",
    "it": "Base topic MQTT",
    "es": "Base del tópico MQTT",
    "pl": "Baza tematów MQTT",
    "uk": "Базова тема MQTT",
    "zh-cn": "MQTT 主题前缀"
  },
  "telemetry_mqtt_username": {
    "en": "MQTT username",
    "de": "MQTT-Benutzername",
    "ru": "Имя пользователя MQTT",
    "pt": "Nome de utilizador MQTT",
    "nl": "MQTT-gebruikersnaam",
    "fr": "Nom d’utilisateur MQTT",
    "it": "Nome utente MQTT",
    "es": "Nombre de usuario MQTT",
    "pl": "Nazwa użytkownika MQTT",
    "uk": "Ім’я користувача MQTT",
    "zh-cn": "MQTT 用户名"
  },
  "telemetry_mqtt_password": {
    "en": "MQTT password",
    "de": "MQTT-Passwort",
    "ru": "Пароль MQTT",
    "pt": "Palavra-passe MQTT",
    "nl": "MQTT-wachtwoord",
    "fr": "Mot de passe MQTT",
    "it": "Password MQTT",
    "es": "Contraseña MQTT",
    "pl": "Hasło MQTT",
    "uk": "Пароль MQTT",
    "zh-cn": "MQTT 密码"
  },
  "telemetry_fields_tab_hint": {
    "en": "The Fleet Telemetry field selection is configured on the <b>Fleet Telemetry fields</b> tab. The adapter stores that selection internally as JSON for compatibility with older versions.",
    "de": "Die Fleet-Telemetry-Feldauswahl wird im Reiter <b>Fleet-Telemetry-Felder</b> konfiguriert. Der Adapter speichert diese Auswahl intern als JSON, damit ältere Versionen kompatibel bleiben.",
    "ru": "Выбор полей Fleet Telemetry настраивается на вкладке <b>Поля Fleet Telemetry</b>. Адаптер хранит этот выбор внутри как JSON для совместимости со старыми версиями.",
    "pt": "A seleção de campos Fleet Telemetry é configurada no separador <b>Campos de Fleet Telemetry</b>. O adaptador guarda essa seleção internamente como JSON para compatibilidade com versões antigas.",
    "nl": "De Fleet Telemetry-veldselectie wordt geconfigureerd op het tabblad <b>Fleet Telemetry-velden</b>. De adapter slaat die selectie intern als JSON op voor compatibiliteit met oudere versies.",
    "fr": "La sélection des champs Fleet Telemetry se configure dans l’onglet <b>Champs Fleet Telemetry</b>. L’adaptateur stocke cette sélection en interne au format JSON pour rester compatible avec les anciennes versions.",
    "it": "La selezione dei campi Fleet Telemetry si configura nella scheda <b>Campi Fleet Telemetry</b>. L’adattatore salva internamente questa selezione come JSON per compatibilità con le versioni precedenti.",
    "es": "La selección de campos de Fleet Telemetry se configura en la pestaña <b>Campos de Fleet Telemetry</b>. El adaptador guarda esa selección internamente como JSON para compatibilidad con versiones anteriores.",
    "pl": "Wybór pól Fleet Telemetry konfiguruje się na karcie <b>Pola Fleet Telemetry</b>. Adapter zapisuje ten wybór wewnętrznie jako JSON dla zgodności ze starszymi wersjami.",
    "uk": "Вибір полів Fleet Telemetry налаштовується на вкладці <b>Поля Fleet Telemetry</b>. Адаптер зберігає цей вибір внутрішньо як JSON для сумісності зі старішими версіями.",
    "zh-cn": "Fleet Telemetry 字段选择在 <b>Fleet Telemetry 字段</b> 选项卡中配置。适配器会将该选择作为 JSON 内部保存，以兼容旧版本。"
  },
  "telemetry_actions_title": {
    "en": "Fleet Telemetry actions",
    "de": "Fleet-Telemetry-Aktionen",
    "ru": "Действия Fleet Telemetry",
    "pt": "Ações Fleet Telemetry",
    "nl": "Fleet Telemetry-acties",
    "fr": "Actions Fleet Telemetry",
    "it": "Azioni Fleet Telemetry",
    "es": "Acciones Fleet Telemetry",
    "pl": "Akcje Fleet Telemetry",
    "uk": "Дії Fleet Telemetry",
    "zh-cn": "Fleet Telemetry 操作"
  },
  "telemetry_action_check_status": {
    "en": "Check Fleet Status",
    "de": "Fleet-Status prüfen",
    "ru": "Проверить статус Fleet",
    "pt": "Verificar estado Fleet",
    "nl": "Fleet-status controleren",
    "fr": "Vérifier l’état Fleet",
    "it": "Controlla stato Fleet",
    "es": "Comprobar estado Fleet",
    "pl": "Sprawdź status Fleet",
    "uk": "Перевірити статус Fleet",
    "zh-cn": "检查 Fleet 状态"
  },
  "telemetry_action_configure": {
    "en": "Configure Fleet Telemetry",
    "de": "Fleet Telemetry konfigurieren",
    "ru": "Настроить Fleet Telemetry",
    "pt": "Configurar Fleet Telemetry",
    "nl": "Fleet Telemetry configureren",
    "fr": "Configurer Fleet Telemetry",
    "it": "Configura Fleet Telemetry",
    "es": "Configurar Fleet Telemetry",
    "pl": "Skonfiguruj Fleet Telemetry",
    "uk": "Налаштувати Fleet Telemetry",
    "zh-cn": "配置 Fleet Telemetry"
  },
  "telemetry_action_read_config": {
    "en": "Read Fleet Config",
    "de": "Fleet-Konfiguration lesen",
    "ru": "Прочитать конфигурацию Fleet",
    "pt": "Ler configuração Fleet",
    "nl": "Fleet-configuratie lezen",
    "fr": "Lire la configuration Fleet",
    "it": "Leggi configurazione Fleet",
    "es": "Leer configuración Fleet",
    "pl": "Odczytaj konfigurację Fleet",
    "uk": "Прочитати конфігурацію Fleet",
    "zh-cn": "读取 Fleet 配置"
  },
  "telemetry_action_delete_config": {
    "en": "Delete Fleet Config",
    "de": "Fleet-Konfiguration löschen",
    "ru": "Удалить конфигурацию Fleet",
    "pt": "Eliminar configuração Fleet",
    "nl": "Fleet-configuratie verwijderen",
    "fr": "Supprimer la configuration Fleet",
    "it": "Elimina configurazione Fleet",
    "es": "Eliminar configuración Fleet",
    "pl": "Usuń konfigurację Fleet",
    "uk": "Видалити конфігурацію Fleet",
    "zh-cn": "删除 Fleet 配置"
  },
  "telemetry_action_result": {
    "en": "Telemetry action result",
    "de": "Ergebnis der Telemetry-Aktion",
    "ru": "Результат действия Telemetry",
    "pt": "Resultado da ação Telemetry",
    "nl": "Resultaat van Telemetry-actie",
    "fr": "Résultat de l’action Telemetry",
    "it": "Risultato azione Telemetry",
    "es": "Resultado de la acción Telemetry",
    "pl": "Wynik akcji Telemetry",
    "uk": "Результат дії Telemetry",
    "zh-cn": "Telemetry 操作结果"
  },
  "telemetry_fields_title": {
    "en": "Fleet Telemetry fields",
    "de": "Fleet-Telemetry-Felder",
    "ru": "Поля Fleet Telemetry",
    "pt": "Campos de Fleet Telemetry",
    "nl": "Fleet Telemetry-velden",
    "fr": "Champs Fleet Telemetry",
    "it": "Campi Fleet Telemetry",
    "es": "Campos de Fleet Telemetry",
    "pl": "Pola Fleet Telemetry",
    "uk": "Поля Fleet Telemetry",
    "zh-cn": "Fleet Telemetry 字段"
  },
  "telemetry_fields_description": {
    "en": "Select exactly which Fleet Telemetry fields should be configured on the vehicle and define the minimum update interval per field. Tesla still sends values only when the value changed and the configured interval has elapsed.",
    "de": "Wähle aus, welche Fleet-Telemetry-Felder am Fahrzeug konfiguriert werden sollen, und lege pro Feld das minimale Aktualisierungsintervall fest. Tesla sendet Werte weiterhin nur dann, wenn sich der Wert geändert hat und das konfigurierte Intervall abgelaufen ist.",
    "ru": "Выберите, какие именно поля Fleet Telemetry должны быть настроены на автомобиле, и задайте минимальный интервал обновления для каждого поля. Tesla всё равно отправляет значения только тогда, когда значение изменилось и настроенный интервал истёк.",
    "pt": "Selecione exatamente quais campos Fleet Telemetry devem ser configurados no veículo e defina o intervalo mínimo de atualização por campo. A Tesla continua a enviar valores apenas quando o valor mudou e o intervalo configurado expirou.",
    "nl": "Selecteer precies welke Fleet Telemetry-velden op het voertuig moeten worden geconfigureerd en stel per veld het minimale update-interval in. Tesla verzendt waarden nog steeds alleen wanneer de waarde is gewijzigd en het geconfigureerde interval is verstreken.",
    "fr": "Sélectionnez précisément les champs Fleet Telemetry à configurer sur le véhicule et définissez l’intervalle minimal de mise à jour par champ. Tesla n’envoie toujours les valeurs que lorsqu’elles ont changé et que l’intervalle configuré est écoulé.",
    "it": "Seleziona esattamente quali campi Fleet Telemetry configurare sul veicolo e definisci l’intervallo minimo di aggiornamento per ogni campo. Tesla invia comunque i valori solo quando il valore è cambiato e l’intervallo configurato è trascorso.",
    "es": "Seleccione exactamente qué campos de Fleet Telemetry deben configurarse en el vehículo y defina el intervalo mínimo de actualización por campo. Tesla sigue enviando valores solo cuando el valor ha cambiado y ha transcurrido el intervalo configurado.",
    "pl": "Wybierz dokładnie, które pola Fleet Telemetry mają zostać skonfigurowane w pojeździe, i ustaw minimalny interwał aktualizacji dla każdego pola. Tesla nadal wysyła wartości tylko wtedy, gdy wartość się zmieniła i upłynął skonfigurowany interwał.",
    "uk": "Виберіть, які саме поля Fleet Telemetry потрібно налаштувати в автомобілі, і задайте мінімальний інтервал оновлення для кожного поля. Tesla все одно надсилає значення лише тоді, коли значення змінилося і налаштований інтервал минув.",
    "zh-cn": "选择要在车辆上配置的 Fleet Telemetry 字段，并为每个字段设置最小更新间隔。Tesla 仍然只会在数值发生变化且配置的间隔已到期时发送数据。"
  },
  "telemetry_fields_note": {
    "en": "Fields tagged with <b>default</b> are the adapter preset. Fields tagged with <b>vehicle_location</b> require the <code>vehicle_location</code> OAuth scope. Unmapped fields are stored under <code>&lt;VIN&gt;.telemetry.fields.&lt;FieldName&gt;</code> as raw telemetry values.",
    "de": "Felder mit <b>Standard</b> gehören zum Adapter-Standardpreset. Felder mit <b>vehicle_location</b> benötigen den OAuth-Scope <code>vehicle_location</code>. Nicht gemappte Felder werden als Rohwerte unter <code>&lt;VIN&gt;.telemetry.fields.&lt;FieldName&gt;</code> gespeichert.",
    "ru": "Поля с меткой <b>по умолчанию</b> входят в стандартный пресет адаптера. Поля с меткой <b>vehicle_location</b> требуют OAuth-scope <code>vehicle_location</code>. Несопоставленные поля сохраняются как сырые значения телеметрии в <code>&lt;VIN&gt;.telemetry.fields.&lt;FieldName&gt;</code>.",
    "pt": "Campos com a etiqueta <b>predefinição</b> pertencem ao preset padrão do adaptador. Campos com <b>vehicle_location</b> requerem o scope OAuth <code>vehicle_location</code>. Campos sem mapeamento são guardados como valores brutos em <code>&lt;VIN&gt;.telemetry.fields.&lt;FieldName&gt;</code>.",
    "nl": "Velden met <b>standaard</b> horen bij de standaardpreset van de adapter. Velden met <b>vehicle_location</b> vereisen de OAuth-scope <code>vehicle_location</code>. Niet-gemapte velden worden als ruwe waarden opgeslagen onder <code>&lt;VIN&gt;.telemetry.fields.&lt;FieldName&gt;</code>.",
    "fr": "Les champs marqués <b>par défaut</b> font partie du préréglage standard de l’adaptateur. Les champs marqués <b>vehicle_location</b> nécessitent le scope OAuth <code>vehicle_location</code>. Les champs non mappés sont enregistrés comme valeurs brutes sous <code>&lt;VIN&gt;.telemetry.fields.&lt;FieldName&gt;</code>.",
    "it": "I campi contrassegnati con <b>predefinito</b> fanno parte del preset standard dell’adattatore. I campi con <b>vehicle_location</b> richiedono lo scope OAuth <code>vehicle_location</code>. I campi non mappati vengono salvati come valori grezzi in <code>&lt;VIN&gt;.telemetry.fields.&lt;FieldName&gt;</code>.",
    "es": "Los campos marcados con <b>predeterminado</b> pertenecen al preset estándar del adaptador. Los campos con <b>vehicle_location</b> requieren el scope OAuth <code>vehicle_location</code>. Los campos sin mapeo se guardan como valores sin procesar en <code>&lt;VIN&gt;.telemetry.fields.&lt;FieldName&gt;</code>.",
    "pl": "Pola oznaczone <b>domyślne</b> należą do standardowego presetu adaptera. Pola oznaczone <b>vehicle_location</b> wymagają scope OAuth <code>vehicle_location</code>. Niezmapowane pola są zapisywane jako surowe wartości w <code>&lt;VIN&gt;.telemetry.fields.&lt;FieldName&gt;</code>.",
    "uk": "Поля з позначкою <b>за замовчуванням</b> належать до стандартного пресету адаптера. Поля з <b>vehicle_location</b> потребують OAuth-scope <code>vehicle_location</code>. Незіставлені поля зберігаються як сирі значення у <code>&lt;VIN&gt;.telemetry.fields.&lt;FieldName&gt;</code>.",
    "zh-cn": "带有 <b>默认</b> 标记的字段属于适配器默认预设。带有 <b>vehicle_location</b> 标记的字段需要 OAuth scope <code>vehicle_location</code>。未映射字段会作为原始 telemetry 值存储在 <code>&lt;VIN&gt;.telemetry.fields.&lt;FieldName&gt;</code> 下。"
  },
  "telemetry_search_field": {
    "en": "Search field",
    "de": "Feld suchen",
    "ru": "Найти поле",
    "pt": "Pesquisar campo",
    "nl": "Veld zoeken",
    "fr": "Rechercher un champ",
    "it": "Cerca campo",
    "es": "Buscar campo",
    "pl": "Szukaj pola",
    "uk": "Пошук поля",
    "zh-cn": "搜索字段"
  },
  "telemetry_category_label": {
    "en": "Category",
    "de": "Kategorie",
    "ru": "Категория",
    "pt": "Categoria",
    "nl": "Categorie",
    "fr": "Catégorie",
    "it": "Categoria",
    "es": "Categoría",
    "pl": "Kategoria",
    "uk": "Категорія",
    "zh-cn": "类别"
  },
  "telemetry_use_default_preset": {
    "en": "Use adapter default preset",
    "de": "Adapter-Standardpreset verwenden",
    "ru": "Использовать стандартный пресет адаптера",
    "pt": "Usar preset padrão do adaptador",
    "nl": "Standaardpreset van adapter gebruiken",
    "fr": "Utiliser le préréglage standard de l’adaptateur",
    "it": "Usa preset predefinito dell’adattatore",
    "es": "Usar preset predeterminado del adaptador",
    "pl": "Użyj domyślnego presetu adaptera",
    "uk": "Використати стандартний пресет адаптера",
    "zh-cn": "使用适配器默认预设"
  },
  "telemetry_enable_visible": {
    "en": "Enable visible",
    "de": "Sichtbare aktivieren",
    "ru": "Включить видимые",
    "pt": "Ativar visíveis",
    "nl": "Zichtbare inschakelen",
    "fr": "Activer les visibles",
    "it": "Abilita visibili",
    "es": "Activar visibles",
    "pl": "Włącz widoczne",
    "uk": "Увімкнути видимі",
    "zh-cn": "启用可见项"
  },
  "telemetry_disable_visible": {
    "en": "Disable visible",
    "de": "Sichtbare deaktivieren",
    "ru": "Отключить видимые",
    "pt": "Desativar visíveis",
    "nl": "Zichtbare uitschakelen",
    "fr": "Désactiver les visibles",
    "it": "Disabilita visibili",
    "es": "Desactivar visibles",
    "pl": "Wyłącz widoczne",
    "uk": "Вимкнути видимі",
    "zh-cn": "禁用可见项"
  },
  "telemetry_reset_visible_intervals": {
    "en": "Reset visible intervals",
    "de": "Sichtbare Intervalle zurücksetzen",
    "ru": "Сбросить интервалы видимых",
    "pt": "Repor intervalos visíveis",
    "nl": "Zichtbare intervallen resetten",
    "fr": "Réinitialiser les intervalles visibles",
    "it": "Reimposta intervalli visibili",
    "es": "Restablecer intervalos visibles",
    "pl": "Resetuj widoczne interwały",
    "uk": "Скинути видимі інтервали",
    "zh-cn": "重置可见项间隔"
  },
  "telemetry_custom_field": {
    "en": "Custom / future field name",
    "de": "Eigenes / zukünftiges Feld",
    "ru": "Пользовательское / будущее поле",
    "pt": "Campo personalizado / futuro",
    "nl": "Aangepast / toekomstig veld",
    "fr": "Champ personnalisé / futur",
    "it": "Campo personalizzato / futuro",
    "es": "Campo personalizado / futuro",
    "pl": "Własne / przyszłe pole",
    "uk": "Власне / майбутнє поле",
    "zh-cn": "自定义 / 未来字段"
  },
  "telemetry_add_custom_field": {
    "en": "Add custom field",
    "de": "Eigenes Feld hinzufügen",
    "ru": "Добавить пользовательское поле",
    "pt": "Adicionar campo personalizado",
    "nl": "Aangepast veld toevoegen",
    "fr": "Ajouter un champ personnalisé",
    "it": "Aggiungi campo personalizzato",
    "es": "Añadir campo personalizado",
    "pl": "Dodaj własne pole",
    "uk": "Додати власне поле",
    "zh-cn": "添加自定义字段"
  },
  "telemetry_table_use": {
    "en": "Use",
    "de": "Nutzen",
    "ru": "Использовать",
    "pt": "Usar",
    "nl": "Gebruiken",
    "fr": "Utiliser",
    "it": "Usa",
    "es": "Usar",
    "pl": "Użyj",
    "uk": "Використати",
    "zh-cn": "使用"
  },
  "telemetry_table_field": {
    "en": "Field",
    "de": "Feld",
    "ru": "Поле",
    "pt": "Campo",
    "nl": "Veld",
    "fr": "Champ",
    "it": "Campo",
    "es": "Campo",
    "pl": "Pole",
    "uk": "Поле",
    "zh-cn": "字段"
  },
  "telemetry_table_category": {
    "en": "Category",
    "de": "Kategorie",
    "ru": "Категория",
    "pt": "Categoria",
    "nl": "Categorie",
    "fr": "Catégorie",
    "it": "Categoria",
    "es": "Categoría",
    "pl": "Kategoria",
    "uk": "Категорія",
    "zh-cn": "类别"
  },
  "telemetry_table_interval": {
    "en": "Interval (seconds)",
    "de": "Intervall (Sekunden)",
    "ru": "Интервал (секунды)",
    "pt": "Intervalo (segundos)",
    "nl": "Interval (seconden)",
    "fr": "Intervalle (secondes)",
    "it": "Intervallo (secondi)",
    "es": "Intervalo (segundos)",
    "pl": "Interwał (sekundy)",
    "uk": "Інтервал (секунди)",
    "zh-cn": "间隔（秒）"
  },
  "telemetry_table_target": {
    "en": "ioBroker target",
    "de": "ioBroker-Ziel",
    "ru": "Цель ioBroker",
    "pt": "Destino ioBroker",
    "nl": "ioBroker-doel",
    "fr": "Cible ioBroker",
    "it": "Destinazione ioBroker",
    "es": "Destino ioBroker",
    "pl": "Cel ioBroker",
    "uk": "Ціль ioBroker",
    "zh-cn": "ioBroker 目标"
  },
  "telemetry_config_preview": {
    "en": "Generated Fleet Telemetry config preview",
    "de": "Vorschau der generierten Fleet-Telemetry-Konfiguration",
    "ru": "Предпросмотр созданной конфигурации Fleet Telemetry",
    "pt": "Pré-visualização da configuração Fleet Telemetry gerada",
    "nl": "Voorbeeld van gegenereerde Fleet Telemetry-configuratie",
    "fr": "Aperçu de la configuration Fleet Telemetry générée",
    "it": "Anteprima configurazione Fleet Telemetry generata",
    "es": "Vista previa de la configuración Fleet Telemetry generada",
    "pl": "Podgląd wygenerowanej konfiguracji Fleet Telemetry",
    "uk": "Попередній перегляд згенерованої конфігурації Fleet Telemetry",
    "zh-cn": "生成的 Fleet Telemetry 配置预览"
  },
  "telemetry_config_preview_note": {
    "en": "This preview is saved into <code>telemetryFieldsJson</code> and sent to the <code>vehicle-command</code> proxy when configuring Fleet Telemetry.",
    "de": "Diese Vorschau wird in <code>telemetryFieldsJson</code> gespeichert und beim Konfigurieren von Fleet Telemetry an den <code>vehicle-command</code>-Proxy gesendet.",
    "ru": "Этот предварительный просмотр сохраняется в <code>telemetryFieldsJson</code> и отправляется прокси <code>vehicle-command</code> при настройке Fleet Telemetry.",
    "pt": "Esta pré-visualização é guardada em <code>telemetryFieldsJson</code> e enviada ao proxy <code>vehicle-command</code> ao configurar Fleet Telemetry.",
    "nl": "Dit voorbeeld wordt opgeslagen in <code>telemetryFieldsJson</code> en bij het configureren van Fleet Telemetry naar de <code>vehicle-command</code>-proxy gestuurd.",
    "fr": "Cet aperçu est enregistré dans <code>telemetryFieldsJson</code> et envoyé au proxy <code>vehicle-command</code> lors de la configuration de Fleet Telemetry.",
    "it": "Questa anteprima viene salvata in <code>telemetryFieldsJson</code> e inviata al proxy <code>vehicle-command</code> durante la configurazione di Fleet Telemetry.",
    "es": "Esta vista previa se guarda en <code>telemetryFieldsJson</code> y se envía al proxy <code>vehicle-command</code> al configurar Fleet Telemetry.",
    "pl": "Ten podgląd jest zapisywany w <code>telemetryFieldsJson</code> i wysyłany do proxy <code>vehicle-command</code> podczas konfiguracji Fleet Telemetry.",
    "uk": "Цей попередній перегляд зберігається в <code>telemetryFieldsJson</code> і надсилається проксі <code>vehicle-command</code> під час налаштування Fleet Telemetry.",
    "zh-cn": "此预览会保存到 <code>telemetryFieldsJson</code>，并在配置 Fleet Telemetry 时发送给 <code>vehicle-command</code> 代理。"
  },
  "telemetry_action_running": {
    "en": "Running {command} ...",
    "de": "{command} wird ausgeführt ...",
    "ru": "Выполняется {command} ...",
    "pt": "A executar {command} ...",
    "nl": "{command} wordt uitgevoerd ...",
    "fr": "Exécution de {command} ...",
    "it": "Esecuzione di {command} ...",
    "es": "Ejecutando {command} ...",
    "pl": "Wykonywanie {command} ...",
    "uk": "Виконується {command} ...",
    "zh-cn": "正在执行 {command} ..."
  },
  "telemetry_action_no_response": {
    "en": "No response from adapter",
    "de": "Keine Antwort vom Adapter",
    "ru": "Нет ответа от адаптера",
    "pt": "Sem resposta do adaptador",
    "nl": "Geen antwoord van adapter",
    "fr": "Aucune réponse de l’adaptateur",
    "it": "Nessuna risposta dall’adattatore",
    "es": "Sin respuesta del adaptador",
    "pl": "Brak odpowiedzi adaptera",
    "uk": "Немає відповіді від адаптера",
    "zh-cn": "适配器无响应"
  },
  "telemetry_action_failed": {
    "en": "Telemetry action failed",
    "de": "Telemetry-Aktion fehlgeschlagen",
    "ru": "Действие Telemetry не удалось",
    "pt": "Ação Telemetry falhou",
    "nl": "Telemetry-actie mislukt",
    "fr": "Échec de l’action Telemetry",
    "it": "Azione Telemetry non riuscita",
    "es": "Error en la acción Telemetry",
    "pl": "Akcja Telemetry nie powiodła się",
    "uk": "Дія Telemetry не вдалася",
    "zh-cn": "Telemetry 操作失败"
  },
  "telemetry_action_finished": {
    "en": "Telemetry action finished",
    "de": "Telemetry-Aktion abgeschlossen",
    "ru": "Действие Telemetry завершено",
    "pt": "Ação Telemetry concluída",
    "nl": "Telemetry-actie voltooid",
    "fr": "Action Telemetry terminée",
    "it": "Azione Telemetry completata",
    "es": "Acción Telemetry finalizada",
    "pl": "Akcja Telemetry zakończona",
    "uk": "Дію Telemetry завершено",
    "zh-cn": "Telemetry 操作完成"
  },
  "telemetry_invalid_json_default": {
    "en": "Telemetry fields JSON is invalid. Using default preset.",
    "de": "Das Telemetry-Felder-JSON ist ungültig. Das Standardpreset wird verwendet.",
    "ru": "JSON полей Telemetry недействителен. Используется стандартный пресет.",
    "pt": "O JSON dos campos Telemetry é inválido. A usar o preset padrão.",
    "nl": "Telemetry-velden-JSON is ongeldig. De standaardpreset wordt gebruikt.",
    "fr": "Le JSON des champs Telemetry est invalide. Le préréglage par défaut est utilisé.",
    "it": "Il JSON dei campi Telemetry non è valido. Verrà usato il preset predefinito.",
    "es": "El JSON de campos Telemetry no es válido. Se usa el preset predeterminado.",
    "pl": "JSON pól Telemetry jest nieprawidłowy. Używany jest preset domyślny.",
    "uk": "JSON полів Telemetry недійсний. Використовується стандартний пресет.",
    "zh-cn": "Telemetry 字段 JSON 无效。将使用默认预设。"
  },
  "telemetry_selected_summary": {
    "en": "{selected} selected fields / {total} available fields",
    "de": "{selected} ausgewählte Felder / {total} verfügbare Felder",
    "ru": "Выбрано полей: {selected} / доступно: {total}",
    "pt": "{selected} campos selecionados / {total} campos disponíveis",
    "nl": "{selected} geselecteerde velden / {total} beschikbare velden",
    "fr": "{selected} champs sélectionnés / {total} champs disponibles",
    "it": "{selected} campi selezionati / {total} campi disponibili",
    "es": "{selected} campos seleccionados / {total} campos disponibles",
    "pl": "{selected} wybranych pól / {total} dostępnych pól",
    "uk": "{selected} вибраних полів / {total} доступних полів",
    "zh-cn": "已选择 {selected} 个字段 / 共 {total} 个可用字段"
  },
  "telemetry_raw_state_target": {
    "en": "Raw value: telemetry.fields.{field}",
    "de": "Rohwert: telemetry.fields.{field}",
    "ru": "Сырое значение: telemetry.fields.{field}",
    "pt": "Valor bruto: telemetry.fields.{field}",
    "nl": "Ruwe waarde: telemetry.fields.{field}",
    "fr": "Valeur brute : telemetry.fields.{field}",
    "it": "Valore grezzo: telemetry.fields.{field}",
    "es": "Valor sin procesar: telemetry.fields.{field}",
    "pl": "Wartość surowa: telemetry.fields.{field}",
    "uk": "Сире значення: telemetry.fields.{field}",
    "zh-cn": "原始值：telemetry.fields.{field}"
  },
  "telemetry_badge_location_scope": {
    "en": "vehicle_location",
    "de": "vehicle_location",
    "ru": "vehicle_location",
    "pt": "vehicle_location",
    "nl": "vehicle_location",
    "fr": "vehicle_location",
    "it": "vehicle_location",
    "es": "vehicle_location",
    "pl": "vehicle_location",
    "uk": "vehicle_location",
    "zh-cn": "vehicle_location"
  },
  "telemetry_badge_default": {
    "en": "default",
    "de": "Standard",
    "ru": "по умолчанию",
    "pt": "predefinição",
    "nl": "standaard",
    "fr": "par défaut",
    "it": "predefinito",
    "es": "predeterminado",
    "pl": "domyślne",
    "uk": "за замовчуванням",
    "zh-cn": "默认"
  },
  "telemetry_all_categories": {
    "en": "All categories",
    "de": "Alle Kategorien",
    "ru": "Все категории",
    "pt": "Todas as categorias",
    "nl": "Alle categorieën",
    "fr": "Toutes les catégories",
    "it": "Tutte le categorie",
    "es": "Todas las categorías",
    "pl": "Wszystkie kategorie",
    "uk": "Усі категорії",
    "zh-cn": "所有类别"
  },
  "telemetry_default_preset_filter": {
    "en": "Adapter default preset",
    "de": "Adapter-Standardpreset",
    "ru": "Стандартный пресет адаптера",
    "pt": "Preset padrão do adaptador",
    "nl": "Standaardpreset van adapter",
    "fr": "Préréglage standard de l’adaptateur",
    "it": "Preset predefinito dell’adattatore",
    "es": "Preset predeterminado del adaptador",
    "pl": "Domyślny preset adaptera",
    "uk": "Стандартний пресет адаптера",
    "zh-cn": "适配器默认预设"
  },
  "telemetry_invalid_field_name": {
    "en": "Invalid field name",
    "de": "Ungültiger Feldname",
    "ru": "Недействительное имя поля",
    "pt": "Nome de campo inválido",
    "nl": "Ongeldige veldnaam",
    "fr": "Nom de champ invalide",
    "it": "Nome campo non valido",
    "es": "Nombre de campo no válido",
    "pl": "Nieprawidłowa nazwa pola",
    "uk": "Недійсна назва поля",
    "zh-cn": "字段名无效"
  },
  "telemetry_category_media": {
    "en": "Media",
    "de": "Medien",
    "ru": "Медиа",
    "pt": "Multimédia",
    "nl": "Media",
    "fr": "Médias",
    "it": "Media",
    "es": "Medios",
    "pl": "Media",
    "uk": "Медіа",
    "zh-cn": "媒体"
  },
  "telemetry_category_user_preference": {
    "en": "User Preference",
    "de": "Benutzereinstellungen",
    "ru": "Пользовательские настройки",
    "pt": "Preferências do utilizador",
    "nl": "Gebruikersvoorkeuren",
    "fr": "Préférences utilisateur",
    "it": "Preferenze utente",
    "es": "Preferencias de usuario",
    "pl": "Preferencje użytkownika",
    "uk": "Налаштування користувача",
    "zh-cn": "用户偏好"
  },
  "telemetry_category_powertrain": {
    "en": "Powertrain",
    "de": "Antrieb",
    "ru": "Силовая установка",
    "pt": "Grupo motopropulsor",
    "nl": "Aandrijflijn",
    "fr": "Groupe motopropulseur",
    "it": "Propulsione",
    "es": "Tren motriz",
    "pl": "Układ napędowy",
    "uk": "Силова установка",
    "zh-cn": "动力系统"
  },
  "telemetry_category_service": {
    "en": "Service",
    "de": "Service",
    "ru": "Сервис",
    "pt": "Serviço",
    "nl": "Service",
    "fr": "Service",
    "it": "Servizio",
    "es": "Servicio",
    "pl": "Serwis",
    "uk": "Сервіс",
    "zh-cn": "服务"
  },
  "telemetry_category_location": {
    "en": "Location",
    "de": "Standort",
    "ru": "Местоположение",
    "pt": "Localização",
    "nl": "Locatie",
    "fr": "Localisation",
    "it": "Posizione",
    "es": "Ubicación",
    "pl": "Lokalizacja",
    "uk": "Місцезнаходження",
    "zh-cn": "位置"
  },
  "telemetry_category_climate": {
    "en": "Climate",
    "de": "Klima",
    "ru": "Климат",
    "pt": "Climatização",
    "nl": "Klimaat",
    "fr": "Climatisation",
    "it": "Clima",
    "es": "Climatización",
    "pl": "Klimatyzacja",
    "uk": "Клімат",
    "zh-cn": "空调"
  },
  "telemetry_category_charging": {
    "en": "Charging",
    "de": "Laden",
    "ru": "Зарядка",
    "pt": "Carregamento",
    "nl": "Laden",
    "fr": "Recharge",
    "it": "Ricarica",
    "es": "Carga",
    "pl": "Ładowanie",
    "uk": "Заряджання",
    "zh-cn": "充电"
  },
  "telemetry_category_driving": {
    "en": "Driving",
    "de": "Fahren",
    "ru": "Вождение",
    "pt": "Condução",
    "nl": "Rijden",
    "fr": "Conduite",
    "it": "Guida",
    "es": "Conducción",
    "pl": "Jazda",
    "uk": "Керування",
    "zh-cn": "驾驶"
  },
  "telemetry_category_safety": {
    "en": "Safety",
    "de": "Sicherheit",
    "ru": "Безопасность",
    "pt": "Segurança",
    "nl": "Veiligheid",
    "fr": "Sécurité",
    "it": "Sicurezza",
    "es": "Seguridad",
    "pl": "Bezpieczeństwo",
    "uk": "Безпека",
    "zh-cn": "安全"
  },
  "telemetry_category_vehicle_configuration": {
    "en": "Vehicle Configuration",
    "de": "Fahrzeugkonfiguration",
    "ru": "Конфигурация автомобиля",
    "pt": "Configuração do veículo",
    "nl": "Voertuigconfiguratie",
    "fr": "Configuration du véhicule",
    "it": "Configurazione veicolo",
    "es": "Configuración del vehículo",
    "pl": "Konfiguracja pojazdu",
    "uk": "Конфігурація автомобіля",
    "zh-cn": "车辆配置"
  },
  "telemetry_category_vehicle_state": {
    "en": "Vehicle State",
    "de": "Fahrzeugzustand",
    "ru": "Состояние автомобиля",
    "pt": "Estado do veículo",
    "nl": "Voertuigstatus",
    "fr": "État du véhicule",
    "it": "Stato veicolo",
    "es": "Estado del vehículo",
    "pl": "Stan pojazdu",
    "uk": "Стан автомобіля",
    "zh-cn": "车辆状态"
  },
  "telemetry_category_other": {
    "en": "Other",
    "de": "Sonstiges",
    "ru": "Другое",
    "pt": "Outros",
    "nl": "Overig",
    "fr": "Autre",
    "it": "Altro",
    "es": "Otro",
    "pl": "Inne",
    "uk": "Інше",
    "zh-cn": "其他"
  },
  "excludeElementList_examples": {
    "en": "Example: charge_history, live_status, backup_history, energy_history, self_consumption_history, self_consumption_history_lifetime, energy_history_lifetime",
    "de": "Beispiel: charge_history, live_status, backup_history, energy_history, self_consumption_history, self_consumption_history_lifetime, energy_history_lifetime",
    "ru": "Пример: charge_history, live_status, backup_history, energy_history, self_consumption_history, self_consumption_history_lifetime, energy_history_lifetime",
    "pt": "Exemplo: charge_history, live_status, backup_history, energy_history, self_consumption_history, self_consumption_history_lifetime, energy_history_lifetime",
    "nl": "Voorbeeld: charge_history, live_status, backup_history, energy_history, self_consumption_history, self_consumption_history_lifetime, energy_history_lifetime",
    "fr": "Exemple : charge_history, live_status, backup_history, energy_history, self_consumption_history, self_consumption_history_lifetime, energy_history_lifetime",
    "it": "Esempio: charge_history, live_status, backup_history, energy_history, self_consumption_history, self_consumption_history_lifetime, energy_history_lifetime",
    "es": "Ejemplo: charge_history, live_status, backup_history, energy_history, self_consumption_history, self_consumption_history_lifetime, energy_history_lifetime",
    "pl": "Przykład: charge_history, live_status, backup_history, energy_history, self_consumption_history, self_consumption_history_lifetime, energy_history_lifetime",
    "uk": "Приклад: charge_history, live_status, backup_history, energy_history, self_consumption_history, self_consumption_history_lifetime, energy_history_lifetime",
    "zh-cn": "示例：charge_history、live_status、backup_history、energy_history、self_consumption_history、self_consumption_history_lifetime、energy_history_lifetime"
  }
};
